In [1]:
db = ["Rohit", " Vikash" , "Ajay" , "raj"]

In [32]:
db[1:3]

[[2, 'Vikash', 2222, 'ok'], [3, 'Ajay', 1111, 'good']]

In [6]:
type(db)

list

In [11]:
db = [
       [ 1,"Rohit",    33333,    "Ok" ],
       [ 2, "Vikash" ,2222, "ok" ], 
       [ 3 ,"Ajay" , 1111, "good" ] 
     ]

In [13]:
len(db)

3

In [16]:
db[1:]

[[2, 'Vikash', 2222, 'ok'], [3, 'Ajay', 1111, 'good']]

In [17]:
import numpy

In [18]:
a = numpy.array(db)

In [20]:
type(a)

numpy.ndarray

In [21]:
a

array([['1', 'Rohit', '33333', 'Ok'],
       ['2', 'Vikash', '2222', 'ok'],
       ['3', 'Ajay', '1111', 'good']], dtype='<U11')

In [30]:
a[1:3,1:2]

array([['Vikash'],
       ['Ajay']], dtype='<U11')

In [32]:
import cv2

In [33]:
photo = cv2.imread('selfie.png')

In [35]:
type(photo)

numpy.ndarray

In [40]:
photo.shape

(960, 960, 3)

In [41]:
b= photo[100:300]

In [92]:
cv2.imwrite("my.jpg" , b)

True

In [95]:
capture = cv2.VideoCapture(0)

In [96]:
pic = capture.read()

In [99]:
pic[0]

True

In [100]:
photo =  pic[1]

In [101]:
cv2.imwrite("Rohit.jpg", photo)

True

In [105]:
cv2.imwrite("Rohit1.jpg" , photo)

True

In [122]:
import numpy

In [126]:
a1 = numpy.array( [ [1,2] , [3,4] , [5,6] ] )

In [141]:
b1 = numpy.array([ [1,1] , [[3,3] ,[5,6] ] ] )

In [142]:
a1.shape

(3, 2)

In [143]:
b1.shape

(2, 2)

In [144]:
c1 = numpy.vstack( (a1, b1) )

In [145]:
c1

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [list([3, 3]), list([5, 6])]], dtype=object)

In [146]:
g1 = numpy.hstack( (a1 , b1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [37]:
a1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [38]:
a1 = numpy.array([ [1,2], [3,4], [5,6]])

In [39]:
b1 = numpy.array([[3, 3],[4, 4],[5, 5]])

In [40]:
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
b1

array([[3, 3],
       [4, 4],
       [5, 5]])

In [42]:
a1.shape

(3, 2)

In [43]:
d1 = numpy.hstack( (a1 , b1))

In [154]:
d1

array([[1, 2, 3, 3],
       [3, 4, 4, 4],
       [5, 6, 5, 5]])

In [35]:
c1 = numpy.vstack((a1 ,b1))